# This is a basic workflow to help you get started with Actions

name: Analyze pull request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1

      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.HEAD_REF }}

      - name: Retrieve entire repository history
        run: |
          git fetch --prune --unshallow

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests
        run: |
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
        
      - name: Run sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=jacksonveroneze
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=xUnitTestSamples
             -Dsonar.cs.opencover.reportsPaths="01-Unit-Tests/xUnitTestSamples.Features.Tests/coverage.opencover.xml, 01-Unit-Tests/xUnitTestSamples.Basic.Tests/coverage.opencover.xml"
             -Dsonar.exclusions="01-Unit-Tests/xUnitTestSamples.Features/**, 01-Unit-Tests/UnitTestSamples.Features.Tests/**"
             -Dsonar.coverage.exclusions="01-Unit-Tests/xUnitTestSamples.Features/**, 01-Unit-Tests/UnitTestSamples.Features.Tests/**"
             -Dsonar.projectVersion	:1.0.0
             -Dsonar.pullrequest.key=${{ github.event.number }}
             -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
             -Dsonar.pullrequest.base=${{ github.BASE_REF }}
             -Dsonar.pullrequest.github.repository=${{ github.repository }}
             -Dsonar.scm.provider=git
             -Dsonar.java.binaries=/tmp

              
              
              
              
              
